AlbertaParadise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('announcements/', include('announcements.urls')),
    path('members/', include('members.urls')),
    path('adminnews/', include('news.urls'))
]

members/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm
from .views import SignUpView, VerifyView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='members/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('verify/<user_id>', VerifyView.as_view(), name='verify')
]

news/urls.py
from django.urls import path, include
from .views import RecentNews, NewsAddView

urlpatterns = [
    path('', RecentNews.as_view(), name='recent_news'),
    path('create/', NewsAddView.as_view(), name='create_news')
]

members/models.py
from django.db import models
from django.contrib.auth.models import User


class OneTimeCode(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)

members/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField, AuthenticationForm
from django.contrib.auth.models import User, Group
from django.forms import CharField, PasswordInput, EmailField, TextInput, NumberInput, Form


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=TextInput(attrs={"autofocus": True}), label='Логин')
    password = CharField(
        label='Пароль',
        strip=False,
        widget=PasswordInput(attrs={"autocomplete": "current-password"}),
    )
    error_messages = {
        "invalid_login": (
            "Неправильно введен логин или пароль, либо пользователь не зарегистрирован"
        ),
        "inactive": ("This account is inactive."),
    }


class RegistrationForm(UserCreationForm):
    password1 = CharField(
        label='Пароль',
        strip=False,
        widget=PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text="Придумайте пароль, который сможете вспомнить, но не сможет подобрать злоумышленник",
    )
    password2 = CharField(
        label="Подтверждение пароля",
        widget=PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text="Введите пароль повторно для подтверждения",
    )
    email = EmailField(label="Email", required=True)

    class Meta:
        model = User
        fields = ("username",
                  "email",
                  "password1",
                  "password2",)
        labels = {"username": "Имя пользователя"}
        help_texts = {"username": "Буквы, цифры и следующие символы @/./+/-/_."}
        field_classes = {'username': UsernameField}

class VerificationForm(Form):
    code = CharField(min_length=6, max_length=6, label='Код подтверждения:',
                     help_text='Код подтверждения был отправлен на почту, указанную при регистрации. '
                               'Если код не приходит - проверьте папку "спам"',
                     widget=NumberInput)

members/views.py
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, FormView
from django.contrib.auth.mixins import PermissionRequiredMixin
from .forms import RegistrationForm, VerificationForm
from .models import OneTimeCode


class SignUpView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'members/signup.html'

    def get_success_url(self):
        return reverse('verify', kwargs={'user_id': self.object.id})


class VerifyView(FormView, PermissionRequiredMixin):
    form_class = VerificationForm
    template_name = 'members/verify.html'
    success_url = reverse_lazy('announcements')
    permission_required = ('members.view_announcements', 'members.add_onetimecode', 'members.view_onetimecode')

    def post(self, request, *args, **kwargs):
        provided_code = request.POST['code']
        user = User.objects.get(pk=kwargs['user_id'])
        actual_code = OneTimeCode.objects.get(user=user).code
        if provided_code == actual_code:
            OneTimeCode.objects.get(user=user).delete()
            registered_group = Group.objects.get(name='Registered')
            registered_group.user_set.remove(user)
            verified_group = Group.objects.get(name='Verified')
            if not request.user.groups.filter(name='Verified').exists():
                verified_group.user_set.add(user)
            super().post(request, *args, **kwargs)
            return HttpResponseRedirect(self.success_url)
        else:
            return self.render_to_response(context={'invalid_code': True})

templates/members/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/members/login.html
{% extends 'default.html' %}

<div class="container">
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Войти">
</form>
{% endblock content %}
</div>

templates/members/signup.html
{% extends 'default.html' %}

<div class="container">
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
</form>
{% endblock content %}
</div>

templates/members/verify.html
{% extends 'default.html' %}

<div class="container">
    {% block content %}
        <form method="post">{% csrf_token %}
            <p>
                <label for="id_code">Код подтверждения:</label>
                <input type="number" name="code" maxlength="6" minlength="6" required="" id="id_code">
                <span class="helptext">Код подтверждения был отправлен на почту, указанную при регистрации. Если код не приходит - проверьте папку "спам"</span>

            </p>
            {% if invalid_code %}
                <p>Код введен неверно!</p>
            {% endif %}
            <input type="submit" value="Отправить">
        </form>
    {% endblock content %}
</div>